// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAVALQ-qpM8ZzTGu1HHeqE4iW3sx6b3cnc',
    appId: '1:95676398553:web:ef81049725b155c0df77c8',
    messagingSenderId: '95676398553',
    projectId: 'ewan-app',
    authDomain: 'ewan-app.firebaseapp.com',
    storageBucket: 'ewan-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyALCXF7F3VQEHBDgMue8Da67QXCJAy2P2k',
    appId: '1:95676398553:android:83051e2e425b1457df77c8',
    messagingSenderId: '95676398553',
    projectId: 'ewan-app',
    storageBucket: 'ewan-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAYngXktq31T3UjOGmimQ_MzOyqcfiWWMw',
    appId: '1:95676398553:ios:dc1b8780bef8e9b8df77c8',
    messagingSenderId: '95676398553',
    projectId: 'ewan-app',
    storageBucket: 'ewan-app.firebasestorage.app',
    androidClientId: '95676398553-kt8pt1ae7mv7j99pe1pc16fv6e58o1sj.apps.googleusercontent.com',
    iosClientId: '95676398553-reum3fsquvst4vl3e5borijge2olabgu.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAYngXktq31T3UjOGmimQ_MzOyqcfiWWMw',
    appId: '1:95676398553:ios:dc1b8780bef8e9b8df77c8',
    messagingSenderId: '95676398553',
    projectId: 'ewan-app',
    storageBucket: 'ewan-app.firebasestorage.app',
    androidClientId: '95676398553-kt8pt1ae7mv7j99pe1pc16fv6e58o1sj.apps.googleusercontent.com',
    iosClientId: '95676398553-reum3fsquvst4vl3e5borijge2olabgu.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAVALQ-qpM8ZzTGu1HHeqE4iW3sx6b3cnc',
    appId: '1:95676398553:web:cfd463167da56364df77c8',
    messagingSenderId: '95676398553',
    projectId: 'ewan-app',
    authDomain: 'ewan-app.firebaseapp.com',
    storageBucket: 'ewan-app.firebasestorage.app',
  );
}
